
try:
    a = int(input("Enter a number"))
    print(a + 3)
except Exception as e:
    print("Some error occured",e)
    # pass
    # print("some error occured")
b = int(input("Enter another number"))
print("You are going fine")
